global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 60
resetOnConfigChange: true
splunkIndex: ''

cloudProvider:
  dockerRegistryUrl: my-registry-url.io
  imagePullSecretName: 'my-registry-secret'
  flavor: openshift

authentication:
  ca:
    enabled: false
    useExternal: false
    externalSecretName: ''
  ssl:
    enabled: false
    useExternal: false
    externalSecretName: ''

caSecretName: ''
caPath: '/usr/local/share/ca-certificates'
caKey: 'ca.crt'

shared:
  authentication:
    opa:
      enabled: true
      customHeaderName: "x-api-key"
      domains: 3d
  ca:
    secretName: ''
    path: '/usr/local/share/ca-certificates'
    key: 'ca.crt'
  db:
    host: "10.0.4.4"
    name: "3d-test"
    port: 5432
    sslEnabled: false
    rejectUnauthorized: true
    secrets:
      useExternal: false
      externalSecretName: ''

image:
  repository: pycsw
  tag: nati-test

servicePort: 8080
internalServicePort: 80
pycswPort: 8000
nodePort: 30018

env:
  loglevel: WARNING
  maxrecords: null
  logfile: ''
  profiles: mc_3d
  logFormat: >-
    %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
    %({x-forwarded-for}i)s %(L)s
  uwsgi:
    processes: 6
    threads: 10
  cors:
    enabled: true
    allowedOrigin: '*'
    allowedHeaders: ''
  db:
    schema: public
    requirePassword: false
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics

resources:
  enabled: true
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

nginx:
  enabled: true
  replicaCount: 1
  image:
    repository: nginx
    tag: 'merge' 
  port: 8080
  internalServicePort: 80
  targetPort: 8080
  nodePort: 30001
  resources:
    enabled: true
    value:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

opa:
  image: openpolicyagent/opa
  imageTag: 0.29.4-envoy-3
  port: 9191
  enableLogging: false
  resources:
    enabled: true
    value:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
envoy:
  image: envoyproxy/envoy
  imageTag: v1.18.3
  port: 6565
  maxRequestBytes: 8192
  resources:
    enabled: true
    value:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi        

route:
  enabled: true
  path: /
  https: true
  timeout:
    enabled: false # defaults to 30s by openshift
    duration: 60s # supported units (us, ms, s, m, h, d)

ingress:
  enabled: false
  path: /
  host: 'localhost'
  cors:
    enabled: true
    origin: '*'
